main:
  - name: "Home"
    url: "/#hero"
    weight: 10

  - name: "About"
    url: "/#about"
    weight: 20

  - name: "Publications"
    url: "/#papers"
    weight: 30

  - name: "Teaching"
    url: "/#teaching"
    weight: 40

  - name: "News"
    url: "/#news"
    weight: 50

  - name: "CV"
    url: "https://maxbradleyeui.github.io/uploads/CV_2026.pdf"
    weight: 60
